### PR TITLE
Add beta support for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by klo2k**
Can't believe the script works on 22.04 with zero tweak!

### CODE REVIEW

**Comment by AndreasNasman** [comment]
Also tested this with Ubuntu 22.04 following [this guide](https://www.nakivo.com/blog/install-ubuntu-20-04-on-hyper-v-with-enhanced-session/) and it seems to work out-of-the-box with the 20.04 script. 🙂

**Comment by klo2k** [comment]
@Hinara do you need more info from me to merge this?

I have another PR coming up fixing the "Authentication required to refresh system repositories." prompt, I'd like to eventually upstream to your repo. once tested:
https://github.com/klo2k/linux-vm-tools/pull/1

**Comment by Hinara** [comment]
Sorry I just have seen it thanks to your message seems good to me

**Comment by ghost** [comment]
Just tested on Lubuntu 23.04 (Lunar Lobster) and it worked with one small hitch. The icon images on the desktop and through the DE went missing (programs/files still opened correctly), changed the icons theme and restored everything. Not sure if there was a better place to post this comment, but here seemed fine.

**Pull request merged**
